[providers]
node = "18.x"

[phases.setup]
nix_pkgs = ["nodejs-18_x", "python3"]

[phases.build]
commands = [
    "npm install",
    "cd react-app && npm install && npm run build"
]

[start]
command = "node server.js"