[[providers]]
name = "node"
version = "18.x"

[phases.setup]
nix_pkgs = ["nodejs-18_x"]

[phases.install]
commands = [
    "npm install",
    "cd react-app && npm install"
]

[phases.build]
commands = [
    "cd react-app && npm run build"
]

[start]
command = "node server.js"
