# nixpacks.toml
[[providers]]
name = "node"
version = "18.x"

[phases.setup]
nix_pkgs = ["nodejs-18_x", "python3"]  # Python je často potřeba pro některé npm balíčky

[phases.install]
commands = ["npm install"]

[phases.build]
commands = [
    "cd react-app && npm install",
    "cd react-app && npm run build"
]

[start]
command = "node server.js"